owner: mrgeneralgoo
repo: status-page
sites:
  - name: Blog
    url: $URL_BLOG
  - name: CDN
    url: $URL_CDN
  - name: Proxy-Main
    url: $URL_PROXY_MAIN
  - name: Proxy-Backup
    url: $URL_PROXY_BACK
  - name: Proxy-Invisible
    url: $URL_PROXY_INVISIBLE
  - name: RSS
    url: $URL_RSS
  - name: Blog(Archived)
    url: $URL_BLOG_ARCHIVED

status-website:
  cname: status.chengxiaobai.com
  logoUrl: https://www.chengxiaobai.com/images/apple-touch-icon.png
  favicon: https://www.chengxiaobai.com/images/favicon-32x32.png
  faviconSvg: https://www.chengxiaobai.com/images/favicon.svg
  name: Chengxiaobai Status
  introTitle: Chengxiaobai System Status
  introMessage: This is the system status for the [Chengxiaobai](https://www.chengxiaobai.com) service.
