owner: mrgeneralgoo
repo: status-page
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/605.1.15 Uptime/$UP_UA
sites:
  - name: Blog
    url: https://www.chengxiaobai.com
  - name: Image
    url: https://cdn.chengxiaobai.com
  - name: Blog(Archived)
    url: https://www.chengxiaobai.cn
  - name: Proxy-T
    url: $URL_PROXY_T
  - name: Proxy-V
    url: $URL_PROXY_V
  - name: RSS
    url: $URL_RSS

status-website:
  cname: status.chengxiaobai.com
  logoUrl: https://www.chengxiaobai.com/images/apple-touch-icon.png
  favicon: https://www.chengxiaobai.com/images/favicon-32x32.png
  faviconSvg: https://www.chengxiaobai.com/images/favicon.svg
  name: Chengxiaobai Status
  introTitle: Chengxiaobai System Status
  introMessage: This is the system status for the Chengxiaobai service.
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://www.chengxiaobai.com
