owner: mrgeneralgoo
repo: status-page
sites:
  - name: Blog
    url: $URL_BLOG
    icon: https://www.chengxiaobai.com/favicon.ico
  - name: CDN
    url: $URL_CDN
    icon: https://www.chengxiaobai.com/favicon.ico
  - name: Proxy-Main
    url: $URL_PROXY_MAIN
    icon: https://avatars.githubusercontent.com/u/33605505
  - name: Proxy-Backup
    url: $URL_PROXY_BACK
    icon: https://avatars.githubusercontent.com/u/49637375
  - name: Proxy-Invisible
    url: $URL_PROXY_INVISIBLE
    icon: https://www.cloudflare.com/favicon.ico
  - name: RSS
    url: $URL_RSS
    icon: https://rsshub.app/favicon.ico
  - name: Blog(Archived)
    url: $URL_BLOG_ARCHIVED
    icon: https://www.chengxiaobai.com/favicon.ico
    expectedStatusCodes:
      - 0
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308

status-website:
  cname: status.chengxiaobai.com
  logoUrl: https://www.chengxiaobai.com/images/apple-touch-icon.png
  favicon: https://www.chengxiaobai.com/images/favicon-32x32.png
  faviconSvg: https://www.chengxiaobai.com/images/favicon.svg
  name: Chengxiaobai Status
  introTitle: Chengxiaobai System Status
  introMessage: This is the system status for the [Chengxiaobai](https://www.chengxiaobai.com) service.
  apiBaseUrl: https://status.chengxiaobai.com/api/?url=https%3A%2F%2Fapi.github.com
  userContentBaseUrl: https://status.chengxiaobai.com/api/?url=https%3A%2F%2Fraw.githubusercontent.com
